server:
  port: 8080

spring:
  #===========bean冲突======#
  main:
    allow-bean-definition-overriding: true

  #============数据库===========#
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootdemo?useSSL=true&useUnicode=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
    # 切换数据源
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      remove-abandoned-on-maintenance:
  jpa:
    hibernate:
      ddl-auto: update # 自动创建表
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect # 指定数据库引擎
  redis:
    host: localhost
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: 100ms
  jackson:
    default-property-inclusion: non_null # json处理时忽空字段





#===========配置elastic search============#
#  elasticsearch:
#    rest:
#      uris: https://192.168.41.88:9200
#      username: elastic
#      password: 123456


#===========rabbitmq===========#
#  rabbitmq:
#    host: 192.168.100.100
  rabbitmq:
    connection-timeout: 60s
    listener:
      simple:
        acknowledge-mode: manual
  #============email===========#
  mail:
    username: m14785769048@163.com
    password: YGEZUISQLBHUJIIM
    host: smtp.163.com
    from: m14785769048@163.com





#============mybatisPlus===========#
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.fql.entity # 类型别名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





